version: '3.1'

services:

  db:
    image: chrislab_mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: wpdatabase
      MARIADB_USER: wpuser
      MARIADB_PASSWORD: wppassword
      MARIADB_ROOT_PASSWORD: wprootpassword 
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: chrislab_wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wpdatabase
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  db:
